# This exposes Power Sensor to the frontend (like Home Assistant). The power 
# value (Watts) for each brightness is estimated from the Skyfan DC light 
# specification.
---
substitutions:
  power_light_name: $light_name power

sensor:
  - id: power_light
    platform: template
    name: ${power_light_name}
    update_interval: 30s
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
    accuracy_decimals: 0
    lambda: |-
      if (id(skyfan_light).state) {
        return (id(skyfan_light).current_values.get_brightness() * 20); 
      } else {
        return 0.0;
      }
    disabled_by_default: true