# This exposes a faux Power Sensor to the frontend (like Home Assistant). 
# The power value (Watts) for each brightness is estimated from the Skyfan DC
# light specification.
#
# **WARNING**
# Untested and incomplete.
---
substitutions:
  power_light_name: $light_name power

sensor:
  - id: power_light
    platform: template
    name: ${power_light_name}
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
    accuracy_decimals: 1
    disabled_by_default: true

interval:
  - interval: 30s
    then:
      - if:
          condition:
            light.is_on: skyfan_light
          then:
            - sensor.template.publish:
                id: power_light
                state: !lambda |-
                  return (id(skyfan_light).current_values.get_brightness() * 20); 
          else:
            - sensor.template.publish:
                id: power_light
                state: !lambda |-
                  return 0.0;
